title: tbash.xyz
email: your-email@example.com
description: >-
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tbash.xyz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .git/
  - .github/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Sass
sass:
  style: compressed
  sass_dir: _sass

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
