title: "Writing observations, thoughts and for my clarity"
description: ""
url: "https://tbash.xyz" # Domain of your site
baseurl: "" # Leave empty since this is your main GitHub Pages site

theme: no-style-please
author: Harsha

# No style please theme settings
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "cd .." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_title: true # show blog title

# Build settings
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md