title: ""
description: "Writing observations, thoughts and for my clarity"
url: "https://tbash.xyz"
baseurl: ""

# Theme settings
theme: jekyll-theme-console
header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # true (default) or false

# Console theme settings
footer: 'follow me on <a href="https://github.com/harshatba">github</a>'
google_analytics: # your google analytics id

# Build settings
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md